apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoisyourbff
  namespace: whoisyourbff
  labels:
    app: whoisyourbff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoisyourbff
  template:
    metadata:
      labels:
        app: whoisyourbff
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: whoisyourbff
          image: ghcr.io/oliwaf/who-is-your-bff-k8s:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8501
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
