apiVersion: v1
kind: Service
metadata:
  name: who-is-your-bff
  labels:
    app: who-is-your-bff
spec:
  type: ClusterIP
  selector:
    app: who-is-your-bff
  ports:
    - name: http
      port: 8501
      targetPort: http
