apiVersion: v1
kind: Service
metadata:
  name: whoisyourbff
  namespace: whoisyourbff
  labels:
    app: whoisyourbff
spec:
  type: ClusterIP
  selector:
    app: whoisyourbff
  ports:
    - name: http
      port: 8501
      targetPort: 8501
